name: CI

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2-beta
      with:
        version: '12'
    - name: Install dependencies
      run: yarn
    - name: Lint
      run: yarn lint
    - name: Test
      run: yarn test --colors
